version: '3.8'
services:
  # Spring Boot Application Service
  spring-app:
    image: managemiqro  # Replace with the actual image for your Spring Boot application
    ports:
      - "8080:8080"
    environment:
      DB_IP: postgres  # Use the service name as the DB_IP
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_DBNAME: ManageDb
    depends_on:
      - postgres

  # PostgreSQL Database Service
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ManageDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
