version: '3'
services:
  frontend:
    image: react
    environment:
      - BACKENDUSERS = localhost
      - BACKENDDEVICES = localhost
    ports:
      - "3000:3000"
  user-app:
    image: usermqrio  # Replace with the actual image for your Spring Boot application
    ports:
      - "8080:8080"
    environment:
      DB_IP: postgres  # Use the service name as the DB_IP
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_DBNAME: UserDb
    depends_on:
      - postgres

  # PostgreSQL Database Service
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: UserDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
      
  device-app:
    image: devicemiqro  # Replace with the actual image for your Spring Boot application
    ports:
      - "8081:8081"
    environment:
      DB_IP: postgres2  # Use the service name as the DB_IP
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_DBNAME: DeviceDB
    depends_on:
      - postgres2
      

    # PostgreSQL Database Service
  postgres2:
    image: postgres:15
    environment:
      POSTGRES_DB: DeviceDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5431:5432"
      
  manage-app:
    image: managemiqro  # Replace with the actual image for your Spring Boot application
    ports:
      - "8082:8082"
    environment:
      DB_IP: postgres3  # Use the service name as the DB_IP
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_DBNAME: ManageDb
    depends_on:
      - postgres3  
      
      
  postgres3:
    image: postgres:15
    environment:
      POSTGRES_DB: ManageDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
  chat-app:
    image: chat  # Replace with the actual image for your Spring Boot application
    ports:
      - "8083:8083"
    